build: CI - Update Review Script

diff --git a/.github/workflows/post-push.yml b/.github/workflows/post-push.yml
--- a/.github/workflows/post-push.yml
+++ b/.github/workflows/post-push.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: Post Push
+name: CreateReviewPR
 
 # Controls when the workflow will run
 on:
@@ -19,38 +19,58 @@ jobs:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
+    env:
+      BRANCHTOMERGE: main
+      LABELS: automated-ci-review
+      REVIEWBRANCH: review-${{github.triggering_actor}}-${{github.sha}}
+      REVIEWCOMMITMSG: (CI) Automated Review Branch Commit
+      PRTITLE: (CI) - Automated Pull Request For Review ${{github.event.head_commit.author}} ${{github.sha}}
+      PRBODY: |
+        ${{github.event.head_commit.author}} has pushed a commit to the dev branch, which has triggered
+        an automated workflow that created a review branch, and submitted this automated PR for review.
+        Message: ${{github.event.head_commit.message}}
+
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
-
-      # Setup Rust Toolchain & Check Code With Rust Fmt
-      - name: Install Rust Toolchain (nightly)
-        uses: dtolnay/rust-toolchain@nightly
-
-      - name: Install Rust Fmt
-        run: rustup component add rustfmt
-      
-      - uses: mbrobbel/rustfmt-check@master
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          mode: commit
-      # Create PR On Main
-      - name: Create PR
-        uses: peter-evans/create-pull-request@v5.0.2
+      # Create Temporary Branch, Commit To That Branch, Then Open PR To Main
+      - name: Checkout Commit
+        uses: actions/checkout@v4
         with:
             token: ${{secrets.GITHUB_TOKEN}}
-            base: main
-            branch: validcommit
-            branch-suffix: random
-            delete-branch: true
-            labels: |
-              report
-              automated pr
-            title: Automated PR From Development Branch
-            body: |
-              This PR Was Generated Because ${{github.actor}}
-              Pushed A Commit To The Development Branch Which Seemingly
-              Passed All Tests In The Current Workflow ${{github.workflow_ref}}.
-              Commit SHA: ${{github.sha}}
-              Commit Message: ${{github.event.head_commit.message}} ${{github.event.head_commit.timestamp}}
+      - run: |
+          echo "Checked Out Branch"
+      - name: Create New Branch
+        run: |
+          gh pr checkout ${{env.REVIEWBRANCH}}
+      - name: Check Success
+        if: ${{ !success() }}
+        run: |
+          echo "(-) Failed To Create Review Branch : ${{env.REVIEWBRANCH}}"
+          exit 1
+      - name: Commit Source To Review Branch ${{env.REVIEWBRANCH}}
+        run: |
+          echo "(*) Attempting To Commit To Review Branch : ${{env.REVIEWBRANCH}}"
+          git status
+          git add .
+          git commit -M ${{env.REVIEWCOMMITMSG}}
+          git push
+
+      - name: Check Success
+        if: ${{ !success() }}
+        run: |
+          echo "(-) Failed To Commit Source To Review Branch : ${{env.REVIEWBRANCH}}"
+          exit 1
+          
+
+      - name: Create Pull Request Into Main For Review
+        run: |
+          echo "(*) Creating Pull Request"
+          gh pr create --base ${{env.BRANCHTOMERGE}} --head ${{env.REVIEWBRANCH}} --title ${{env.PRTITLE}} --body ${{env.PRBODY}} --label ${{env.LABELS}}
+      
+      - name: Check Success
+        if: ${{ !success() }}
+        run: |
+          echo "(-) Failed To Create Pull Request For Review"
+
+          
+
